import 'dart:convert';
import 'package:http/http.dart' as http;
import '../models/ai_response.dart';
import 'ai_service.dart';

class CustomApiService implements AIService {
  final String apiKey;
  final String endpoint;
  final String model;

  CustomApiService({
    required this.apiKey,
    required this.endpoint,
    required this.model,
  });

  String _cleanJsonResponse(String rawText) {
    var cleaned = rawText.trim();
    if (cleaned.startsWith('```json')) {
      cleaned = cleaned.substring(7);
    } else if (cleaned.startsWith('```')) {
      cleaned = cleaned.substring(3);
    }
    if (cleaned.endsWith('```')) {
      cleaned = cleaned.substring(0, cleaned.length - 3);
    }
    return cleaned.trim();
  }

  Future<Map<String, dynamic>> _callCustomApi(String prompt) async {
    final targetEndpoint = endpoint.trim().isEmpty
        ? 'https://api.openai.com/v1/chat/completions'
        : endpoint.trim();

    final url = Uri.parse(targetEndpoint);

    final headers = <String, String>{
      'Content-Type': 'application/json',
    };
    if (apiKey.trim().isNotEmpty) {
      headers['Authorization'] = 'Bearer ${apiKey.trim()}';
    }

    try {
      final response = await http.post(
        url,
        headers: headers,
        body: jsonEncode({
          'model': model.trim().isEmpty ? 'gpt-4o-mini' : model.trim(),
          'messages': [
            {
              'role': 'system',
              'content':
                  'You are FluentAI, a helpful English writing assistant. Always respond strictly in valid JSON.'
            },
            {'role': 'user', 'content': prompt}
          ],
          'temperature': 0.3,
        }),
      );

      if (response.statusCode != 200) {
        throw AIServiceException(
            'Custom API Error (Status ${response.statusCode}): ${response.body}');
      }

      final resData = jsonDecode(response.body);
      final choices = resData['choices'] as List<dynamic>?;
      if (choices == null || choices.isEmpty) {
        throw const AIServiceException('Empty response received from Custom API Endpoint.');
      }

      final content = choices[0]['message']?['content'] as String?;
      if (content == null || content.trim().isEmpty) {
        throw const AIServiceException('No content generated by Custom API.');
      }

      final cleanedText = _cleanJsonResponse(content);
      return jsonDecode(cleanedText) as Map<String, dynamic>;
    } on AIServiceException {
      rethrow;
    } catch (e) {
      throw AIServiceException('Custom API Service Error: ${e.toString()}');
    }
  }

  @override
  Future<GrammarResult> correctGrammar(String text) async {
    final prompt = '''
Check text for grammar, spelling, punctuation, and style issues.
Respond strictly in JSON format with exact keys:
"correctedText": (string),
"explanation": (string)

Input Text:
"$text"
''';
    final json = await _callCustomApi(prompt);
    return GrammarResult.fromJson(json, text);
  }

  @override
  Future<SentenceCorrectionResult> correctSentence(String sentence, String style) async {
    final prompt = '''
Rephrase sentence in "$style" style.
Respond strictly in JSON with keys:
"primaryCorrection": (string),
"alternatives": (array of strings),
"explanation": (string),
"keyImprovements": (array of strings)

Original Sentence:
"$sentence"
''';
    final json = await _callCustomApi(prompt);
    return SentenceCorrectionResult.fromJson(json, sentence);
  }

  @override
  Future<DraftResult> generateDraft({
    required String prompt,
    required String tone,
    required String type,
    String? replyToMessage,
  }) async {
    final isReply = replyToMessage != null && replyToMessage.trim().isNotEmpty;
    final contextPrompt = isReply
        ? 'Reply to: "$replyToMessage"\nInstructions: "$prompt"\nType: $type\nTone: $tone'
        : 'Draft $type based on: "$prompt"\nTone: $tone';

    final fullPrompt = '''
$contextPrompt
Respond strictly in JSON with keys:
"subjectLine": (string or null),
"generatedDraft": (string),
"keyPointsCovered": (array of strings)
''';

    final json = await _callCustomApi(fullPrompt);
    return DraftResult.fromJson(json, type, tone);
  }

  @override
  Future<DictionaryResult> lookupWord(String word) async {
    final prompt = '''
Dictionary lookup for: "$word".
Respond strictly in JSON with keys:
"word": (string),
"pronunciation": (string),
"partOfSpeech": (string),
"definitions": (array of strings),
"exampleSentences": (array of strings),
"originNote": (string)
''';
    final json = await _callCustomApi(prompt);
    return DictionaryResult.fromJson(json, word);
  }

  @override
  Future<SynonymsResult> fetchSynonymsAndAntonyms(String word) async {
    final prompt = '''
Find synonyms and antonyms for word: "$word".
Respond strictly in JSON with keys:
"word": (string),
"synonyms": (array of strings),
"antonyms": (array of strings),
"contextNote": (string)
''';
    final json = await _callCustomApi(prompt);
    return SynonymsResult.fromJson(json, word);
  }

  @override
  Future<SentenceMakerResult> makeSentences(String topicOrWord) async {
    final prompt = '''
Generate sample sentences for: "$topicOrWord".
Respond strictly in JSON with keys:
"topicOrWord": (string),
"beginnerSentences": (array of 3 strings),
"intermediateSentences": (array of 3 strings),
"advancedSentences": (array of 3 strings),
"usageTips": (string)
''';
    final json = await _callCustomApi(prompt);
    return SentenceMakerResult.fromJson(json, topicOrWord);
  }
}
