import 'dart:convert';
import 'package:http/http.dart' as http;
import '../models/ai_response.dart';
import 'ai_service.dart';

class GeminiService implements AIService {
  final String apiKey;
  final String model;

  GeminiService({required this.apiKey, required this.model});

  String _cleanJsonResponse(String rawText) {
    var cleaned = rawText.trim();
    if (cleaned.startsWith('```json')) {
      cleaned = cleaned.substring(7);
    } else if (cleaned.startsWith('```')) {
      cleaned = cleaned.substring(3);
    }
    if (cleaned.endsWith('```')) {
      cleaned = cleaned.substring(0, cleaned.length - 3);
    }
    return cleaned.trim();
  }

  Future<Map<String, dynamic>> _callGeminiApi(String prompt) async {
    if (apiKey.trim().isEmpty) {
      throw const AIServiceException(
          'Gemini API key is missing. Please set your API key in Settings.');
    }

    final modelName = model.trim().isEmpty ? 'gemini-2.5-flash' : model.trim();
    final url = Uri.parse(
        'https://generativelanguage.googleapis.com/v1beta/models/$modelName:generateContent?key=${apiKey.trim()}');

    try {
      final response = await http.post(
        url,
        headers: {'Content-Type': 'application/json'},
        body: jsonEncode({
          'contents': [
            {
              'parts': [
                {'text': prompt}
              ]
            }
          ],
          'generationConfig': {
            'temperature': 0.3,
            'responseMimeType': 'application/json',
          }
        }),
      );

      if (response.statusCode != 200) {
        final errJson = jsonDecode(response.body);
        final errMsg = errJson['error']?['message'] ??
            'Gemini API error (Status ${response.statusCode})';
        throw AIServiceException(errMsg);
      }

      final resData = jsonDecode(response.body);
      final candidates = resData['candidates'] as List<dynamic>?;
      if (candidates == null || candidates.isEmpty) {
        throw const AIServiceException('Empty response received from Gemini API.');
      }

      final text = candidates[0]['content']?['parts']?[0]?['text'] as String?;
      if (text == null || text.trim().isEmpty) {
        throw const AIServiceException('No text output generated by Gemini.');
      }

      final cleanedText = _cleanJsonResponse(text);
      return jsonDecode(cleanedText) as Map<String, dynamic>;
    } on AIServiceException {
      rethrow;
    } catch (e) {
      throw AIServiceException('Gemini Service Error: ${e.toString()}');
    }
  }

  @override
  Future<GrammarResult> correctGrammar(String text) async {
    final prompt = '''
You are an expert English grammar assistant. Check the text below for grammar, spelling, punctuation, and phrasing errors.
Respond ONLY with a valid JSON object with the exact keys:
"correctedText": (string, corrected version of text),
"explanation": (string, clear summary of what was corrected and why)

Input Text:
"$text"
''';
    final json = await _callGeminiApi(prompt);
    return GrammarResult.fromJson(json, text);
  }

  @override
  Future<SentenceCorrectionResult> correctSentence(
      String sentence, String style) async {
    final prompt = '''
You are an expert sentence editor. Rephrase and refine the sentence below using the target style: "$style".
Respond ONLY with a valid JSON object with exact keys:
"primaryCorrection": (string, best rephrased version),
"alternatives": (array of 2-3 strings, other good phrasing options),
"explanation": (string, concise explanation of the changes made),
"keyImprovements": (array of strings, bullet points of key structural/vocabulary improvements)

Original Sentence:
"$sentence"
''';
    final json = await _callGeminiApi(prompt);
    return SentenceCorrectionResult.fromJson(json, sentence);
  }

  @override
  Future<DraftResult> generateDraft({
    required String prompt,
    required String tone,
    required String type,
    String? replyToMessage,
  }) async {
    final isReply = replyToMessage != null && replyToMessage.trim().isNotEmpty;
    final contextPrompt = isReply
        ? '''
You are drafting a reply to the following received message:
"$replyToMessage"

User's response instructions: "$prompt"
Type: $type
Tone: $tone
'''
        : '''
Write a clear, professional $type draft based on this prompt: "$prompt".
Tone: $tone
''';

    final fullPrompt = '''
$contextPrompt
Respond ONLY with a valid JSON object with exact keys:
"subjectLine": (string, optional subject line if applicable, else null),
"generatedDraft": (string, full formatted text of the draft),
"keyPointsCovered": (array of strings, bullet list of main points included)
''';

    final json = await _callGeminiApi(fullPrompt);
    return DraftResult.fromJson(json, type, tone);
  }

  @override
  Future<DictionaryResult> lookupWord(String word) async {
    final prompt = '''
Provide dictionary details for the English word/phrase: "$word".
Respond ONLY with a valid JSON object with exact keys:
"word": (string, exact word),
"pronunciation": (string, IPA or phonetic representation e.g. /fld.nt/),
"partOfSpeech": (string, e.g., Adjective, Noun, Verb),
"definitions": (array of strings, 2-4 clear definitions),
"exampleSentences": (array of strings, 3 practical example sentences),
"originNote": (string, brief word origin or usage tip)
''';
    final json = await _callGeminiApi(prompt);
    return DictionaryResult.fromJson(json, word);
  }

  @override
  Future<SynonymsResult> fetchSynonymsAndAntonyms(String word) async {
    final prompt = '''
Provide synonyms and antonyms for the word: "$word".
Respond ONLY with a valid JSON object with exact keys:
"word": (string),
"synonyms": (array of 6-10 strings, relevant synonyms),
"antonyms": (array of 4-8 strings, opposite words),
"contextNote": (string, brief nuance note on usage)
''';
    final json = await _callGeminiApi(prompt);
    return SynonymsResult.fromJson(json, word);
  }

  @override
  Future<SentenceMakerResult> makeSentences(String topicOrWord) async {
    final prompt = '''
Generate sample English sentences for the word or topic: "$topicOrWord".
Respond ONLY with a valid JSON object with exact keys:
"topicOrWord": (string),
"beginnerSentences": (array of 3 simple sentences for beginners),
"intermediateSentences": (array of 3 intermediate complexity sentences),
"advancedSentences": (array of 3 advanced / sophisticated sentences),
"usageTips": (string, practical advice on how to use this word/topic naturally)
''';
    final json = await _callGeminiApi(prompt);
    return SentenceMakerResult.fromJson(json, topicOrWord);
  }
}
